### PR TITLE
Fix BC2 alpha decompression

### PR DESCRIPTION
**Pull request by w-flo**
I noticed the alpha channel was slightly off for every other pixel of my decompressed-then-recompressed-in-an-atlas textures, this change appears to fix it and it appears to match original libsquish code.

### CODE REVIEW

**Comment by jansol** [comment]
Looking at the diff it makes sense since the erroneous values *are* the high bits to begin with so shifting them even higher is obviously wrong when you think about it.

Would you mind adding a regression test to go with the fix?

**Comment by w-flo** [comment]
Thanks for looking at this so soon. And sure, I will add a regression test (hopefully later today) :-)

**Comment by w-flo** [comment]
This one works for me (and it didn't work 2 commits ago, so that's good). It's almost the same as the existing BC1 colour test.

**Comment by jansol** [comment]
Can you change the test data so the alpha has different patterns for the low and high bits and OR'ing them together the wrong way does not provide a correct result? Say, `0xA5` i.e. `0b1010_0101` so basically a checkerboard of 0xAA and 0x55 alphas.

**Comment by w-flo** [comment]
I decided to use 0x00, 0x11, 0x22, … 0xFF for the uncompressed alpha values. That way it ensures that compressed low/high 4 bits are used in the correct order as you suggested, and it also ensures that values end up in the correct uncompressed pixels (out of all 16 possible pixels in a block) and vice versa, to guard against incorrect iteration order (like, the format could theoretically say that the list of compressed alpha bytes need to be stored in reversed order or something, but that's apparently not the case).

The way hexadecimal and decimal literals are mixed in that array is a bit awkward, but I wasn't sure if you'd prefer to have them all in hex (longer lines and it's no longer obvious that it's the same as the earlier test), or all in decimal (makes the relation to the alpha shifting logic less obvious), or if this is acceptable as a compromise. :D

Let me know if I should change any styling etc. or feel free to take it and change it, if that's easier for you.

**Comment by jansol** [comment]
That pattern is even better.

Please keep the encoding consistent within a single array at least. I don't have a particularly strong preference for one encoding or another in this case. All hex would be easier to keep aligned neatly but that's about it. The comment on top of the pixel array does clarify the meaning of the alpha values sufficiently I think, no need to do acrobatics with the encoding of the literal just for that. Line length is something I'm not overly pedantic about as long as it stays reasonable and rustfmt handles it consistently. I think rustfmt defaults to 100 columns wide?

**Comment by w-flo** [comment]
rustfmt defaults to 100 characters for normal code lines, but it limits line length to less than that for "special lines" like function signatures and apparently array definitions for some reason (unless you add a rustfmt.toml to tell it not to). The current formatting is already too wide for rustfmt, but since rustfmt also changes a bunch of other stuff in the code, I didn't know you wanted it to be "rustfmted".

So I'll split each pixel row into two code lines to make rustfmt happy, and convert everything in that array to hex.

**Comment by jansol** [comment]
I haven't looked into rustfmt settings yet but my main motivation with that is to be able to just have formatting done automagically so I don't have to think about it. If adding a rustfmt.toml with `array_width = 100` takes care of this that's a good enough solution for me. If you come across other things that rustfmt handles in an inconvenient/silly way I'm open to further customization as well.

**Comment by w-flo** [comment]
Using hex literals, the array is too wide even for 100 columns because of the 0x prefix, so I think that's not needed. I can just add more lines instead. :-)

**Comment by w-flo** [comment]
I'm not sure why github is not showing my most recent commit in this pull request activity timeline, but I've pushed a new commit to the PR and I see it in the "Commits" tab.

**Comment by jansol** [comment]
Thanks!

**Pull request merged**
