### PR TITLE
Optionally use rayon to (de)compress in paralllel

### PR DESCRIPTION
**Pull request by arturoc**
Squish-cli implements a parallel compression algorithm using rayon.

This PR adds instead a compression and decompression implementation in the library itself which can be activated by using the rayon feature

### CODE REVIEW

**Comment by jansol** [comment]
Nice, thanks for the PR!

This does make the API a bit nicer and more convenient to use. I'm not very familiar with cargo features but it seems like this leaves rayon off by default on the library and turns it on by default in the cli?

**Comment by arturoc** [comment]
yes that's it, you need to explicitly enable rayon when using the library and the cli app enables it by default

**Comment by arturoc** [comment]
it would be really useful to have a release in crates.io with this changes

**Comment by jansol** [comment]
Agreed. I was meaning to do that after I fix BC1 to have separate enum variants for RGB and RGBA images, but never got around to write that part and eventually forgot. Since the current code already breaks API compared to the crates.io release I'd like to avoid breaking it again right after another release.

**Pull request merged**
